CREATE TABLE IF NOT EXISTS messungen (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datum TEXT,
  zeitangabe TEXT,
  unixzeit INTEGER,
  temperatur REAL,
  feuchtigkeit REAL,
  bodenfeuchtigkeit REAL,
  elektrischeLeitfaehigkeit REAL,
  phWert REAL,
  lichtintensitaet REAL,
  co2 REAL,
  pflanzenId INTEGER
);

CREATE TABLE IF NOT EXISTS pflanzen (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    art TEXT
);

CREATE TABLE IF NOT EXISTS wetterdaten (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_temp DOUBLE,
    aqi INTEGER,
    city_name VARCHAR(255),
    clouds INTEGER,
    country_code VARCHAR(2),
    datetime VARCHAR(20),
    dewpt DOUBLE,
    dhi DOUBLE,
    dni DOUBLE,
    elev_angle DOUBLE,
    ghi DOUBLE,
    gust DOUBLE,
    h_angle DOUBLE,
    lat DOUBLE,
    lon DOUBLE,
    ob_time VARCHAR(20),
    pod VARCHAR(1),
    precip DOUBLE,
    pres DOUBLE,
    rh INTEGER,
    slp DOUBLE,
    snow DOUBLE,
    solar_rad DOUBLE,
    state_code VARCHAR(2),
    station VARCHAR(10),
    sunrise VARCHAR(5),
    sunset VARCHAR(5),
    temp DOUBLE,
    timezone VARCHAR(50),
    ts BIGINT,
    uv DOUBLE,
    vis DOUBLE,
    weather_icon VARCHAR(10),
    weather_description VARCHAR(255),
    weather_code INTEGER,
    wind_cdir VARCHAR(1),
    wind_cdir_full VARCHAR(50),
    wind_dir INTEGER,
    wind_spd DOUBLE
);

CREATE TABLE IF NOT EXISTS wetterAPI (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_temp VARCHAR(255),
    aqi VARCHAR(255),
    city_name VARCHAR(255),
    clouds VARCHAR(255),
    country_code VARCHAR(255),
    datetime VARCHAR(255),
    dewpt VARCHAR(255),
    dhi VARCHAR(255),
    dni VARCHAR(255),
    elev_angle VARCHAR(255),
    ghi VARCHAR(255),
    gust VARCHAR(255),
    h_angle VARCHAR(255),
    lat VARCHAR(255),
    lon VARCHAR(255),
    ob_time VARCHAR(255),
    pod VARCHAR(255),
    precip VARCHAR(255),
    pres VARCHAR(255),
    rh VARCHAR(255),
    slp VARCHAR(255),
    snow VARCHAR(255),
    solar_rad VARCHAR(255),
    state_code VARCHAR(255),
    station VARCHAR(255),
    sunrise VARCHAR(255),
    sunset VARCHAR(255),
    temp VARCHAR(255),
    timezone VARCHAR(255),
    ts VARCHAR(255),
    uv VARCHAR(255),
    vis VARCHAR(255),
    icon VARCHAR(255),
    description VARCHAR(255),
    code VARCHAR(255),
    wind_cdir VARCHAR(255),
    wind_cdir_full VARCHAR(255),
    wind_dir VARCHAR(255),
    wind_spd VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS weathericon (id INTEGER PRIMARY KEY AUTOINCREMENT, weather_id VARCHAR(255), description VARCHAR(255), weather_code VARCHAR(255), icon BLOB);
